### ISSUE TITLE
模型分割部分疑问？

### ISSUE THREAD

**Issue by cs-xiao** [hellopipu/TC-MGAN#1]
你好，看了文中写提升分割效果那一块，是通过Gan将其它3种模态补全，然后和t2进行通道cat方式得到seg网络的输入，这个网络和用于补助Gan训练的分割网络不是同一个吧？
如果不是同一个，那这部分的代码也还没有在本库见到，所以产生了这个疑问，望解答3Q~

**Comment by hellopipu** [comment]
hi, the two segment networks are different, [train_pre_unet.py](https://github.com/hellopipu/TC-MGAN/blob/master/train_pre_unet.py) for the one joint training in GAN, [train_unet_4.py](https://github.com/hellopipu/TC-MGAN/blob/master/train_unet_4.py) for the other testing the seg imrovment

**Comment by cs-xiao** [comment]
> hi, the two segment networks are different, [train_pre_unet.py](https://github.com/hellopipu/TC-MGAN/blob/master/train_pre_unet.py) for the one joint training in GAN, [train_unet_4.py](https://github.com/hellopipu/TC-MGAN/blob/master/train_unet_4.py) for the other testing the seg imrovment

ok，get it~，Thanks for your time！
