### ISSUE TITLE
NameError: name 'LAMBDA_CLS' is not defined

### ISSUE THREAD

**Issue by LucyGarlapati** [hellopipu/TC-MGAN#2]

**Comment by hellopipu** [comment]
hi, LAMBDA_REC =0.1 , LAMBDA_CLS = 10, LAMBDA_SEG = 50, LAMBDA_GP = 100 for reference

**Comment by LucyGarlapati** [comment]
Thank you.
Can you please provide Dataset

**Comment by LucyGarlapati** [comment]
Even the trained model link is not working

**Comment by hellopipu** [comment]
hi Lucy, I don't have the dataset on hand, please download the dataset from the official website. And I will update the model link later, sorry for that.

**Comment by LucyGarlapati** [comment]
Thank You for the update
